Repository micronaut-projects/micronaut-microstream, pull requests merged in 2023-06, with the labels that each got.

#212 ci: renovate schedule
  .github/renovate.json
Labels: relates-to: build

#216 [microstream] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
Labels: relates-to: build

#223 add documentation about dependencies for s3
  src/main/docs/guide/storageTargets/s3.adoc
Labels: type: docs

#221 ci: slsa 1.7.0
  .github/workflows/release.yml
Labels: relates-to: build

#225 MicroStream to Micronaut Core 4.0.0-RC1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#229 fix microstream group id
  src/main/docs/guide/cache/cacheConfiguration.adoc
Labels: type: docs

#231 Dynamo and SQL dependencies to docs
  src/main/docs/guide/storageTargets/dynamodb.adoc
  src/main/docs/guide/storageTargets/postgres.adoc
Labels: type: docs

#232 MicroStream to RC3
  gradle/libs.versions.toml
Labels: type: dependency-upgrade
